name: Test
on:
  push:
    branches:
      - new-branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: SFDigitalServices/wait-for-deployment-action@v1
        id: deployment
        with:
          github-token: ${{ secrets.WEBSITE_TESTS_ACCESS_TOKEN }}
          interval: 30
          timeout: 1000
      - run: |
          echo "Deployed to"