name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: wbeuil/wait-for-deployment@v1.0.0
        id: deployment
        with:
          token: ${{ secrets.WEBSITE_TESTS_ACCESS_TOKEN }}
      - run: |
          echo "Deployed tto ${{ steps.deployment.outputs.url }}"
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sergeibakaev
          repo: website-tests
          github_token: ${{ secrets.WEBSITE_TESTS_ACCESS_TOKEN }}
          inputs: '{ "deployed_url": "${{ steps.deployment.outputs.url }}" }'
          workflow_file_name: e2e.yml