name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: SFDigitalServices/wait-for-deployment-action@v1
        id: deployment
        with:
          github-token: ${{ secrets.WEBSITE_TESTS_ACCESS_TOKEN }}
          environment: Preview
      - run: |
          echo "Deployed to"