name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for the Vercel Preview
        uses: sergeibakaev/wait-for-vercel-preview@v1.2.1
        id: deployment
        with:
          token: ${{ github.token }}
          max_timeout: 1000
          check_interval: 5
      # access preview url
      - run: echo ${{steps.deployment.outputs.url}}
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: sergeibakaev
          repo: website-tests
          github_token: ${{ github.token }}
          inputs: '{ "deployed_url": "${{ steps.deployment.outputs.url }}" }'
          workflow_file_name: e2e.yml